package me.darragh.javatinybasic.interpreter;

/**
 * Represents an event that is triggered when the interpreter produces output.
 * This can be used to capture or display the output generated by the interpreter.
 *
 * @author darraghd493
 * @since 1.0.0
 */
@FunctionalInterface
public interface InterpreterOutputEvent {
    /**
     * Handles the output produced by the interpreter.
     *
     * @param output The output string generated by the interpreter.
     */
    void onOutput(String output);
}
